"""initial_schema_baseline

Revision ID: 8f6d4850cfea
Revises: 
Create Date: 2025-12-08 01:14:07.040829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6d4850cfea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('recon_id', sa.String(), nullable=True),
    sa.Column('bank_ref', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_trades_date'), 'broker_trades', ['date'], unique=False)
    op.create_index(op.f('ix_broker_trades_id'), 'broker_trades', ['id'], unique=False)
    op.create_index(op.f('ix_broker_trades_isin'), 'broker_trades', ['isin'], unique=False)
    op.create_index(op.f('ix_broker_trades_symbol'), 'broker_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_broker_trades_tenant_id'), 'broker_trades', ['tenant_id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'tenant_id', name='uq_holding_symbol_tenant')
    )
    op.create_index(op.f('ix_holdings_date'), 'holdings', ['date'], unique=False)
    op.create_index(op.f('ix_holdings_id'), 'holdings', ['id'], unique=False)
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    op.create_index(op.f('ix_holdings_tenant_id'), 'holdings', ['tenant_id'], unique=False)
    op.create_table('learning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('trade_data', sa.JSON(), nullable=True),
    sa.Column('correction_notes', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nav_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('fund_name', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('nav_value', sa.Float(), nullable=True),
    sa.Column('aum', sa.Float(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nav_logs_id'), 'nav_logs', ['id'], unique=False)
    op.create_index(op.f('ix_nav_logs_tenant_id'), 'nav_logs', ['tenant_id'], unique=False)
    op.create_table('recon_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('cash_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('status_before', sa.String(), nullable=True),
    sa.Column('status_after', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('agent_model', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recon_logs_id'), 'recon_logs', ['id'], unique=False)
    op.create_index(op.f('ix_recon_logs_tenant_id'), 'recon_logs', ['tenant_id'], unique=False)
    op.create_table('rule_definitions',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('tier', sa.Enum('TIER_1_DETERMINISTIC', 'TIER_2_TOLERANCE', 'TIER_3_AI', name='ruletier'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tolerance_threshold', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('rule_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('pattern_hash', sa.String(), nullable=True),
    sa.Column('learned_rule_json', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('times_applied', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_memory_pattern_hash'), 'rule_memory', ['pattern_hash'], unique=False)
    op.create_index(op.f('ix_rule_memory_tenant_id'), 'rule_memory', ['tenant_id'], unique=False)
    op.create_table('bank_txns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trade_ref', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trade_ref'], ['broker_trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_txns_date'), 'bank_txns', ['date'], unique=False)
    op.create_index(op.f('ix_bank_txns_id'), 'bank_txns', ['id'], unique=False)
    op.create_index(op.f('ix_bank_txns_tenant_id'), 'bank_txns', ['tenant_id'], unique=False)
    op.create_table('recon_breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('cash_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('break_type', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='breakseverity'), nullable=True),
    sa.Column('amount_diff', sa.Float(), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cash_id'], ['bank_txns.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rule_definitions.rule_id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['broker_trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recon_breaks_id'), 'recon_breaks', ['id'], unique=False)
    op.create_index(op.f('ix_recon_breaks_tenant_id'), 'recon_breaks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recon_breaks_tenant_id'), table_name='recon_breaks')
    op.drop_index(op.f('ix_recon_breaks_id'), table_name='recon_breaks')
    op.drop_table('recon_breaks')
    op.drop_index(op.f('ix_bank_txns_tenant_id'), table_name='bank_txns')
    op.drop_index(op.f('ix_bank_txns_id'), table_name='bank_txns')
    op.drop_index(op.f('ix_bank_txns_date'), table_name='bank_txns')
    op.drop_table('bank_txns')
    op.drop_index(op.f('ix_rule_memory_tenant_id'), table_name='rule_memory')
    op.drop_index(op.f('ix_rule_memory_pattern_hash'), table_name='rule_memory')
    op.drop_table('rule_memory')
    op.drop_table('rule_definitions')
    op.drop_index(op.f('ix_recon_logs_tenant_id'), table_name='recon_logs')
    op.drop_index(op.f('ix_recon_logs_id'), table_name='recon_logs')
    op.drop_table('recon_logs')
    op.drop_index(op.f('ix_nav_logs_tenant_id'), table_name='nav_logs')
    op.drop_index(op.f('ix_nav_logs_id'), table_name='nav_logs')
    op.drop_table('nav_logs')
    op.drop_table('learning_events')
    op.drop_index(op.f('ix_holdings_tenant_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_date'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_broker_trades_tenant_id'), table_name='broker_trades')
    op.drop_index(op.f('ix_broker_trades_symbol'), table_name='broker_trades')
    op.drop_index(op.f('ix_broker_trades_isin'), table_name='broker_trades')
    op.drop_index(op.f('ix_broker_trades_id'), table_name='broker_trades')
    op.drop_index(op.f('ix_broker_trades_date'), table_name='broker_trades')
    op.drop_table('broker_trades')
    # ### end Alembic commands ###
